let naam= "Liv";
let level= 23;
let strenght=  17.3;
let speed= 20;
let stamina= 10;
let powers= "flight";
let lives= 4;
let health= 350;
let weapon= "spear";
let respawn= true;
console.log("name: " + naam);
console.log("level: " + level);
console.log("strenght: " + strenght);
console.log("speed: " + speed);
console.log("stamina: " + stamina);
console.log("powers: " + powers);
console.log("lives: " + lives);
console.log("health: " + health);
console.log("weapon: " + weapon);
console.log("talent: " + respawn);